[project]
name = "fastapi-course-freecodecamp"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.128.0",
    "pyrefly>=0.47.0",
    "uvicorn>=0.40.0",
]
